version: "3.8"
services:
  react:
    build:
      context: ./my-gallery
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
     - ./my-gallery:/frontend/react
    environment:
     - CHOKIDAR_USEPOLLING=true
  dotnet:
    build:
      context: ./Api-service-dotnet
      dockerfile: Dockerfile.dev
    ports:
      - "5108:5108"
      - "7286:7286"
    volumes:
      - ./Api-service-dotnet:/backend/dotnet
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"