FROM mcr.microsoft.com/dotnet/sdk:6.0-focal

WORKDIR /backend/dotnet

COPY *.csproj .
COPY appsettings.json ./

RUN dotnet restore
RUN dotnet dev-certs https --trust

COPY . .

EXPOSE 7286
EXPOSE 5108

ENTRYPOINT dotnet watch run --urls=http://+:5108;http://+:7286 --project MyPersonalGallery.csproj